language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
script: bundle exec rake travis
before_script:
  - psql -c 'create database todo_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
services:
  - postgresql
