language: ruby
rvm:
  - 1.9.3
  - 2.0.0
script: bundle exec rake foo
before_script:
  - cp config/database.yml.travis config/database.yml
services:
  - postgresql
notifications:
  email:
    recipients:
      - crigor@rigprog.com
